//
// Created by jr156 on 13/4/2026.
//

#ifndef PROYECTO1F_OPERACIONICONSISTENTEEXC_H
#define PROYECTO1F_OPERACIONICONSISTENTEEXC_H


class OperacionIconsistenteExc {
};


#endif //PROYECTO1F_OPERACIONICONSISTENTEEXC_H